### ISSUE TITLE
Fedora ARM build status

### ISSUE THREAD

**Issue by jbuck** [jbuck/CDOT-Dashboard#7]
We should display a list of packages that the ARM servers are building, and their pass/warning/failed status

**Comment by cadecairos** [comment]
I've got working code to display the statuses of builds on packages. I based it off of this page here: http://arm.koji.fedoraproject.org/koji/builds?order=-completion_time

It displays 12 items and changes the background colour depending on its' status. It only works on static test data at the moment as there is not live data available.

here's the code: https://github.com/cadecairos/CDOT-Dashboard/tree/fedoraArm
